# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hAssow2lzpcmfMTtrJ7Z2FfOR3YylzVW
"""

#Instituição: Uninassau
#Docente: Cloves Rocha
#Estudante: Fabio San

f="fabio"
print("Tipo do dado: ",type(f))
print(type(f))


#3. Operadores Aritméticos - Guia Aprender Python

#10 + 9   Adição
#9 * 8    Multiplicação
#9 - 7    Divisão
#10 / 3   Divisão
#5 ** 3   Exponenciação
#10 // 3  Divisão Inteira
#10 % 3   Resto da divisão

f = 2**3
print(f,'exponenciação')
f = 2//3
print(f,'divisão inteira')
f = 10%3
print(f,'resto da divisao')

#operadores relacionais simples

# 7 > 10
# 9 < 8

a= 10
b= 8

a == b